# Generated by Django 5.0.6 on 2024-07-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transtactions', '0002_alter_transaction_options_alter_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_bankrupt',
            field=models.BooleanField(default=False),
        ),
    ]
